# Generated by Django 4.2.4 on 2023-08-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='invite_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
